workflows:
  my-workflow:
    name: Hello World Workflow
    instance_type: mac_pro
    max_build_duration: 120
    environment:
      vars:
        MY_VAR: "Hello Codemagic"
    scripts:
      - name: Say hello
        script: echo $MY_VAR
